### ISSUE TITLE
Error pip install -U doge-datagen

### ISSUE THREAD

**Issue by Stefen-Taime** [getindata/doge-datagen#19]
ERROR: Failed building wheel for confluent-kafka
  Running setup.py clean for confluent-kafka
Failed to build confluent-kafka
Installing collected packages: confluent-kafka, doge-datagen
    Running setup.py install for confluent-kafka ... error

**Comment by gliter** [comment]
Could you try on fresh virtual env? It might be something with your environment.
I tried to reproduce:
```
$ python3 -m venv ~/.virtualenvs/tmp1
$ source ~/.virtualenvs/tmp1/bin/activate
$ pip install -U doge-datagen
...
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 confluent-kafka-1.8.2 doge-datagen-1.0.4 fastavro-1.4.10 greenlet-1.1.2 idna-3.3 psycopg2-binary-2.9.3 requests-2.27.1 sqlalchemy-1.4.35 urllib3-1.26.9
```

**Comment by Stefen-Taime** [comment]
yess thanks :)
